spring.application.name=activityservice

# MongoDB Configuration

spring.data.mongodb.uri=mongodb://localhost:27017/activityservice
spring.data.mongodb.database=activityservice

# Server Port
server.port=8081
